=== CoffeeCat0815/digital-commissioning-tool/DigitalCommissioningTool/Output/Ressources/Data/ConfigSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Ressources/Data" 
           targetNamespace="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Ressources/Data"
           elementFormDefault="qualified" attributeFormDefault="qualified">

<!-- definition of Simple Elements -->
  <xs:element name="value" type="xs:string"/>
  
<!-- definition of Attributes -->
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="id" type="xs:long"/>
  <xs:attribute name="type" type="xs:string"/>
  <xs:attribute name="value" type="xs:string"/>
  <xs:attribute name="isArray" type="xs:boolean"/>
  <xs:attribute name="elementCount" type="xs:unsignedLong"/>
  <xs:attribute name="propertyCount" type="xs:unsignedLong"/>
  <xs:attribute name="dataCount" type="xs:long"/>
    
<!-- definition of Complex elements -->
  <xs:element name="values">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="propertyCount" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="property">
    <xs:complexType>
      <xs:attribute ref="type" use="required"/>
      <xs:attribute ref="value" use="required"/>
    </xs:complexType>
  </xs:element> 
  
  <xs:element name="simpleData">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="value" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute ref="type" use="required"/>
      <xs:attribute ref="isArray" use="required"/>
      <xs:attribute ref="elementCount" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="complexData">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="values" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="type" use="required"/>
      <xs:attribute ref="id" use="required"/>
      <xs:attribute ref="isArray" use="required" fixed="false"/>
      <xs:attribute ref="elementCount" use="required" fixed="1"/>
    </xs:complexType>
  </xs:element>

  <xs:group name="data">
    <xs:choice>
      <xs:element ref="simpleData"/>
      <xs:element ref="complexData"/>
    </xs:choice>
  </xs:group>

  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="data" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="dataCount" use="required"/>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== CoffeeCat0815/digital-commissioning-tool/DigitalCommissioningTool/Output/Ressources/Data/settings.xml
<?xml version="1.0" encoding="utf-8"?>
<xs:Config xs:dataCount="7" xmlns:xs="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Ressources/Data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Ressources/Data ConfigSchema.xsd">
    <xs:simpleData xs:name="ExampleText1" xs:id="1" xs:type="String" xs:isArray="false" xs:elementCount="1">
        <xs:value>Das ist ein sehr langer Text! mit einigen Satzeichen, der beim Testen hilft?</xs:value>
    </xs:simpleData>
    <xs:simpleData xs:name="ExampleText2" xs:id="2" xs:type="Int32" xs:isArray="false" xs:elementCount="1">
        <xs:value>123456789</xs:value>
    </xs:simpleData>
    <xs:simpleData xs:name="ExampleText3" xs:id="3" xs:type="Double" xs:isArray="false" xs:elementCount="1">
        <xs:value>145346.67</xs:value>
    </xs:simpleData>
    <xs:simpleData xs:name="ExampleText4" xs:id="4" xs:type="Char" xs:isArray="false" xs:elementCount="1">
        <xs:value>@</xs:value>
    </xs:simpleData>
    <xs:simpleData xs:name="ExampleText5" xs:id="5" xs:type="Boolean" xs:isArray="false" xs:elementCount="1">
        <xs:value>False</xs:value>
    </xs:simpleData>
    <xs:simpleData xs:name="WorkingDirectory" xs:id="6" xs:type="String" xs:isArray="false" xs:elementCount="1">
        <xs:value>C:\Users\Stefan\Documents\GitHub\digital-commissioning-tool\DigitalCommissioningTool</xs:value>
    </xs:simpleData>
    <xs:complexData xs:name="TestClass" xs:id="7" xs:type="objectData" xs:isArray="false" xs:elementCount="1">
        <xs:values xs:propertyCount="2">
            <xs:property xs:type="Double" xs:value="815">
            </xs:property>
            <xs:property xs:type="String" xs:value="Hallo Welt!">
            </xs:property>
        </xs:values>
    </xs:complexData>
</xs:Config>

=== CoffeeCat0815/digital-commissioning-tool/DigitalCommissioningTool/Output/Ressources/Data/Paths.xml
<?xml version="1.0" encoding="utf-8"?>
<xs:Config xs:dataCount="4" xmlns:xs="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Ressources/Data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Ressources/Data ConfigSchema.xsd">
    <xs:simpleData xs:name="StringRessourcePathDebug" xs:id="1" xs:type="String" xs:isArray="false" xs:elementCount="1">
        <xs:value>.\Output\Ressources\Strings\</xs:value>
    </xs:simpleData>
    <xs:simpleData xs:name="StringRessourcePathDebug" xs:id="2" xs:type="String" xs:isArray="false" xs:elementCount="1">
        <xs:value>.\Ressources\Strings\</xs:value>
    </xs:simpleData>
    <xs:simpleData xs:name="LogPathDebug" xs:id="3" xs:type="String" xs:isArray="false" xs:elementCount="1">
        <xs:value>.\Output\Logs\</xs:value>
    </xs:simpleData>
    <xs:simpleData xs:name="LogPathDebug" xs:id="4" xs:type="String" xs:isArray="false" xs:elementCount="1">
        <xs:value>.\Logs\</xs:value>
    </xs:simpleData>
</xs:Config>
