=== CoffeeCat0815/digital-commissioning-tool/DigitalCommissioningTool/Output/Ressources/Strings/StringRessourceSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Ressources/Strings" 
           targetNamespace="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Ressources/Strings"
           elementFormDefault="qualified" attributeFormDefault="qualified">

<!-- definition of Simple Elements -->
<xs:element name="value" type="xs:string"/>
   
<!-- definition of Attributes -->
<xs:attribute name="name" type="xs:string"/>
<xs:attribute name="id" type="xs:long"/>
<xs:attribute name="lang" type="xs:string"/>
  
<!-- definition of Complex elements -->
  <xs:element name="string">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="value" maxOccurs="1" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="id" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="StringRessources">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="string" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="lang" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CoffeeCat0815/digital-commissioning-tool/DigitalCommissioningTool/Output/Ressources/Strings/deu.xml
<?xml version="1.0" encoding="utf-8"?>
<StringRessources lang="deu" xmlns="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Ressources/Strings" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/xShadowArmy/digital-commissioning-tool/tree/main/DigitalCommissioningTool/Output/Ressources/Strings StringRessourceSchema.xsd">
	<string name="test1" id="1">
		<value>Das ist ein Teststring1</value>
	</string>
	
	<string name="test2" id="2">
		<value>Das ist ein Teststring2</value>
	</string>
	
	<string name="test3" id="3">
		<value>Das ist ein Teststring3</value>
	</string>
	
	<string name="test4" id="4">
		<value>Das ist ein Teststring4</value>
	</string>
	
	<string name="test5" id="5">
		<value>Das ist ein Teststring5</value>
	</string>
	
	<string name="test6" id="6">
		<value>Das ist ein Teststring6</value>
	</string>
	
	<string name="test7" id="7">
		<value>Das ist ein Teststring7</value>
	</string>
	
	<string name="test8" id="8">
		<value>Das ist ein Teststring8</value>
	</string>
	
	<string name="ErrorText" id="9">
		<value>Das ist ein Text der einen Fehler darstellen soll!</value>
	</string>
</StringRessources>
